### PR TITLE
Apple Music: Fix albums without name, increase cooldown periode on 504 gateway timeouts.

### PR DESCRIPTION
**Pull request by MarvinSchenkel**
Fix albums without name. Increase cooldown periode on 504 timeout. Also add some more logging to the 504 so we can see the request that is timing out

### CODE REVIEW

**Review by marcelveldt — APPROVED** [review]

**Comment by MarvinSchenkel** [comment]
Do they fail after 5 retries? Or do you see it picking up after 2 or 3 retries? I have not been able to find a root cause. Might be Apple.. Might be some edge cases in your library (e.g. purchased music, custom uploaded music etc..).

**Comment by faelenor** [comment]
They always fail after 5 retries. I've never been able to sync any track.

**Comment by MarvinSchenkel** [comment]
Alright, could you please open an issue and provide some debug logs? Maybe we can find a pattern and figure out what is going wrong. Please also describe your library, does it just consists of online content, did you upload custom stuff, did you purchase music etc...

**Comment by faelenor** [comment]
Ok, I'll do this, thanks! Do you know why the logs are always truncated? I can only see the last couple of KBs, both in the addon page and the settings/system/log section.

**Pull request merged**
