### PR TITLE
Fix snapcast client_id

### PR DESCRIPTION
**Pull request by SantiagoSotoC**

### CODE REVIEW

**Review by marcelveldt — CHANGES_REQUESTED** [review]
you should create a small helper method to get/calculate the player id

**Comment by SantiagoSotoC** [comment]
Yes, that's why I created a draft. I wanted to see if it works in the dev addon, but I couldn't.

**Comment by SantiagoSotoC** [comment]
I will test it well, when I know that everything works fine I mark the pr as ready for review.

**Comment by marcelveldt** [comment]
> Yes, that's why I created a draft. I wanted to see if it works in the dev addon, but I couldn't.

the dev-addon can just checkout a branch you give it. for pr's you need to specify it a bit fancy, I believe you can specify: pr/1220

**Comment by SantiagoSotoC** [comment]
I'll try it now thanks, when I see the volume I'll do it directly in the repo.

**Comment by SantiagoSotoC** [comment]
This way of doing it will not work, some clients use "-" in the identifier (snapweb). I think the solution will be to create a dictionary and generate internal identifiers.

**Pull request closed without merging**
