### PR TITLE
Snapcast update 0.29

### PR DESCRIPTION
**Pull request by SantiagoSotoC**
Should we use snapcast as a package or snapcast-server ? 
snapcast includes snapclient as well.

### CODE REVIEW

**Comment by marcelveldt** [comment]
snapcast package is fine as we need snapclient as well soon for the local player I'm working

**Review by marcelveldt — APPROVED** [review]
how stable is the 0.29 version and what does it (potentially) fix that we want it already ?

**Comment by SantiagoSotoC** [comment]
it is stable, it has 2 months without complaints, version 8 snapweb corresponds to 0.29

**Comment by SantiagoSotoC** [comment]
But with snapcast it is not clear how to test it, the documentation is not very clear.

**Pull request merged**
