### PR TITLE
Fix similar tracks function

### PR DESCRIPTION
**Pull request by jozefKruszynski**
Fixes issue: https://github.com/music-assistant/hass-music-assistant/issues/1475

### CODE REVIEW

**Comment by MarvinSchenkel** [comment]
Ruff is failing so we cannot merge this :(. Probably also need to remove the limit here: https://github.com/music-assistant/server/blob/01d3bfe982499da3107cbdf660a26f427b50ed65/music_assistant/server/providers/tidal/__init__.py#L319

**Comment by jozefKruszynski** [comment]
> Ruff is failing so we cannot merge this :(. Probably also need to remove the limit here:
> 
> https://github.com/music-assistant/server/blob/01d3bfe982499da3107cbdf660a26f427b50ed65/music_assistant/server/providers/tidal/__init__.py#L319
> 
> and in the helper function to keep ruff happy.

Ooooh, this is a real stinker as I would also have to remove it from the function in __init__.py. This won't work, so I'll have to add an exemption to the method for now I think

**Comment by MarvinSchenkel** [comment]
> 

I think just removing it from the helper function will be fine for now.

**Comment by MarvinSchenkel** [comment]
> 

Yes you are right, I just edited my answer :)

**Review by MarvinSchenkel — APPROVED** [review]

**Pull request merged**
