### PR TITLE
Added seek_position to JellyfinProvider's get_audio_stream function

### PR DESCRIPTION
**Pull request by lyonzy**
I was seeing a few of these in my logs:

```
TypeError: JellyfinProvider.get_audio_stream() takes 2 positional arguments but 3 were given
```

And it looked like get_audio_stream was missing seek_position. I changed it to use get_http_stream, copied from `URLProvider`, because it supports seeking - hope that's alright.

### CODE REVIEW

**Review by marcelveldt — APPROVED** [review]
Great!

**Comment by marcelveldt** [comment]
The linter found some formatting issues.
TIP: use pre-commit to test the code for you: from within your development venv: pre-commit install

**Comment by lyonzy** [comment]
Sure, should be passing the linter now (I'll admit to being a bit lazy and not really setting everything up when I did the original change).

**Comment by marcelveldt** [comment]
there was another lint issue, I fixed it for you

**Pull request merged**
