### PR TITLE
YTMusic: Fix missing metadata for Artists on library sync

### PR DESCRIPTION
**Pull request by MarvinSchenkel**
Fixes missing thumbs and descriptions during initial library sync. Previously, Artists were added as ItemMappings because of the missing info. However, those were never refreshed unless the were actively clicked on by the user. With this change, full artist details will be fetched during the library sync from YT Music, also relieving some stress on MusicBrainz.

### CODE REVIEW

**Review by marcelveldt — CHANGES_REQUESTED** [review]
I'm not sure I can agree with this. This will result in a shitshow of requests against their api if I'm reading this right ?

ItemMapping exists to prevent all these additional per-item calls.

**Comment by MarvinSchenkel** [comment]
> I'm not sure I can agree with this. This will result in a shitshow of requests against their api if I'm reading this right ?
> 
> ItemMapping exists to prevent all these additional per-item calls.

True, but the side effect is an artist overview without any thumbs and other Metadata. Somehow a force refresh on these item mappings do not result in resolving the artist from either ytm or music brains, so th user is left with empty Metadata here.

Also, these additional requests are only made during the sync.

**Comment by marcelveldt** [comment]
Let's concentrate on the issue then. By default artists (that go into the db from albums or tracks) wont have metadata unless you first click them. Is that not working ? Then we should fix that. Doing a full artist lookup at every sync is really way too heavy. What we can do however if this is really wanted, direct the request to the artists controller, as that will use the cache.

so instead of grabbing the artist within your own provider, do it by using mass.music.artists.get_provider_item

Another approach we could consider is restoring the background check but with a lot more caution to prevent too many calls.

**Comment by MarvinSchenkel** [comment]
> Let's concentrate on the issue then. By default artists (that go into the db from albums or tracks) wont have metadata unless you first click them. Is that not working ? Then we should fix that. Doing a full artist lookup at every sync is really way too heavy. What we can do however if this is really wanted, direct the request to the artists controller, as that will use the cache.
> 
> so instead of grabbing the artist within your own provider, do it by using mass.music.artists.get_provider_item
> 
> Another approach we could consider is restoring the background check but with a lot more caution to prevent too many calls.

Yeah I have to agree with this. First things first, I'll see if I can figure out why an item mapping is never updated with the full details. I can see the request coming in in the YT Music provider's get_artist but it never reaches the update_db in the artist controller.

**Comment by marcelveldt** [comment]
superseded by https://github.com/music-assistant/server/pull/1480

**Pull request closed without merging**
